---
server:
  http:
    address: "127.0.0.1:8080"
    crypto_key: private-key.pem
  grpc:
    address: "127.0.0.1:8081"
  storage:
    store_interval: 20s
  sign_key: test
  log_level: "DEBUG"

agent:
  log_level: "DEBUG"
  poller:
    poll_interval: 10s
  reporter:
    sign_key: test
    server_address: "127.0.0.1:8080"
    grpc_server_address: "127.0.0.1:8081"
    crypto_key: public-key.pem
