---
server:
  address: "127.0.0.1:8080"
  log_level: "DEBUG"
  store_interval: 20s
  sign_key: test
  crypto_key: private-key.pem

agent:
  poller:
    poll_interval: 10s
  reporter:
    sign_key: test
    server_address: "127.0.0.1:8081"
    crypto_key: public-key.pem
